# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a7dd1544549aa0c904701366a071f04accdcd792c2a254d432ad24527f291000193ce37de89b41a1db5247e21836ff111866890c1defe4a3d52d152b8e23082

test:
  secret_key_base: 529b6cca0883480422eb2b246fa5e8a03c732aeee51110e224ca2ef731ffe9a547fef09aabe1c5d77508462085b2ac1b0ed1073682aa9ec5646ac1ff1f696f8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
